[package]
name = "netkitty"
version = "0.1.0"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]
edition = "2018"

[dependencies]
async-std = "*"
futures = "*"
paw = "*"
structopt = { version = "*", features = [ "paw" ] }
